[package]
name = "wasabi"
version = "0.1.0"
edition = "2024"

[dependencies]
termion = "4.0.5"
tokio = { version = "1.47.1", features = ["sync", "net", "rt", "macros", "rt-multi-thread"] }
tokio-tungstenite = "0.27.0"
tungstenite = "0.27.0"
futures-util = "0.3.31"